// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh-ImCJMnZTSi4l9qgoUnGQDIhcvz2y3U',
    appId: '1:849897017725:web:2099bed1d01c8a58157c14',
    messagingSenderId: '849897017725',
    projectId: 'wr-app-130039404',
    authDomain: 'wr-app-130039404.firebaseapp.com',
    databaseURL: 'https://wr-app-130039404-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wr-app-130039404.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrvSPbPCA0GVfcYyABuf5mpVjOQXMucR0',
    appId: '1:849897017725:android:d933e8b62d7e5e27157c14',
    messagingSenderId: '849897017725',
    projectId: 'wr-app-130039404',
    databaseURL: 'https://wr-app-130039404-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wr-app-130039404.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjFRmx--xeY5hu25r4onaThr-8E1djN9E',
    appId: '1:849897017725:ios:c92703fb594f76d9157c14',
    messagingSenderId: '849897017725',
    projectId: 'wr-app-130039404',
    databaseURL: 'https://wr-app-130039404-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wr-app-130039404.appspot.com',
    iosClientId: '849897017725-b9i3b808opp4vnk0ftlngjtqo335dvgq.apps.googleusercontent.com',
    iosBundleId: 'com.example.wrapp',
  );
}
